### ISSUE TITLE
Broken link to Waddle

### ISSUE THREAD

**Issue by opinner** [EagleoutIce/portfolio#9]
I just looked through your portfolio out of interest and found that the Waddle link https://sp2.informatik.uni-ulm.de/waddle seems to be broken. Maybe you didn't realize that yet.

**Comment by EagleoutIce** [comment]
Oh no thanks for noticing, the link changed just recently!

**Comment by EagleoutIce** [comment]
I fix this in <https://github.com/EagleoutIce/portfolio/pull/10>
